### ISSUE TITLE
iOS: Could not load file or assembly 'Google.Maps'

### ISSUE THREAD

**Issue by T-T-P** [themronion/Maui.GoogleMaps#1]
Hi,

I have come across an error when trying to run on iOS (simulator or device), this occurs both in my own application as well as the sample application?

> Could not load file or assembly 'Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

Any assistance would be greatly appreciated.

Many Thanks in advance for your help and for porting this to MAUI :)

**Comment by themronion** [comment]
Sorry for my late response. Is it still reproducible?

**Comment by T-T-P** [comment]
No problem, yes, I'm afraid I've been unable to resolve this, it just seems to crash out on any iOS device or the simulator at present.

**Comment by themronion** [comment]
I'll update to the latest MAUI stuff and take a look

**Comment by themronion** [comment]
Does it happen in release mode or debug or both? I've tried in debug and didn't reproduce. Anyway i've published a new nuget with .net 7, try it out

**Comment by T-T-P** [comment]
It was happening in both debug and release however I've now had a chance to test out your .net 7 nuget and that seems to be working perfect in the simulator. I'm not quite at the point to try release mode on .net 7 version but will let you know, it should be fine though if working on simulator in debug. Many thanks for your assistance in getting this working, it's very much appreciated :)

**Comment by themronion** [comment]
You are welcome) Closing this issue then, feel free to reopen if needed

**Comment by T-T-P** [comment]
I have had a chance to test further in both debug and release mode and unfortunately get an Objective-C based error occurring in certain situations.

> "Objective-C exception thrown.  Name: GMSServicesException Reason: Google Maps SDK for iOS must be initialized via [GMSServices provideAPIKey:...] prior to use"

I think I have narrowed it down to occurring when a Google Map is used on the first ContentPage the app shows, if another ContentPage is shown first (in my case a login screen) the Map will then work perfectly in debug and release.

I have the line `builder.UseGoogleMaps(Variables.GOOGLE_MAPS_IOS_API_KEY, platformConfig);` in the MauiProgram file so think this may be something occurring deeper within the Maui.GoogleMaps implementation (apologies if not)?

If you have any ideas, I would be most grateful as digging into the Maui.GoogleMaps code itself is a little above me at the present time 😄

**Comment by themronion** [comment]
Send me some code to reproduce the issue without your api keys and i'll help
