### ISSUE TITLE
Document Using MauiImage As Pin

### ISSUE THREAD

**Issue by T-T-P** [themronion/Maui.GoogleMaps#13]
### SUMMARY

There does not currently appear to be any details or documentation of how to use "MauiImage" as a pin for the map, only stream or embedded resources seems to work as was the case in the Xamarin repository that was forked from.

### DETAILS

Please could an example and/or documentation be created for using the "MauiImage" type as a pin on the map? This may require changes to the Maui.GoogleMaps package?

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
A MauiImage in the end is nothing else but a .png in the native resources folders. The sample repo has MauiImage usage examples - image01, image02, image03. Please use BitmapDescriptorFactory.FromBundle()

**Comment by T-T-P** [comment]
Apologies @themronion I missed that part of the sample. Could I ask, is there any way to resize the icon (width/height) when using FromBundle() as it doesn't automatically resize in the same way that FromStream() does when using an EmbeddedResource?

**Comment by themronion** [comment]
U can specify the size in the MauiImage tag in the csproj, that will be your base size for the icon

**Comment by Quaedrikk** [comment]
Hello @themronion , is it possible to do the resizing depending on the zoom size? I am trying to resize pin icons depending on map zoom and cannot seem to figure out how to achieve this. Thanks!

**Comment by themronion** [comment]
@Quaedrikk i don't completely understand what you need. Maybe u are looking for `Scale` property on the pin? Do u have a video of what u want to achieve?

**Comment by Quaedrikk** [comment]
I am trying to add numbered rooms into a building, however the pins i am using for the numbers do not scale down when i zoom in and cause visual clutter. I was unable to find any scale property on the pin or pinicon. Attached are screenshots of  three levels of zoom with the same pins. If you need more clarification please let me know!
![Screenshot 2024-07-05 162952](https://github.com/themronion/Maui.GoogleMaps/assets/74473730/4eeec196-86fb-42a4-8e94-ea4d985e1c94)
![Screenshot 2024-07-05 162943](https://github.com/themronion/Maui.GoogleMaps/assets/74473730/45d8a737-cf5d-4747-a223-1d24291262c7)
![Screenshot 2024-07-05 162935](https://github.com/themronion/Maui.GoogleMaps/assets/74473730/b1b9209c-b83f-4ae5-be6d-72ada2030b08)
