### ISSUE TITLE
Java Lang Exception image must be a bitmap.

### ISSUE THREAD

**Issue by Jalroka** [themronion/Maui.GoogleMaps#15]
### VERSIONS

* Maui.GoogleMaps - x.x.x
* .NET SDK - x.x.x

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ x] Android
- [] iOS

### ACTUAL BEHAVIOR
```
// Write about of your problem
```
When I'm adding a pin to the map I'm getting an error about a Java.Lang.IllegalArgumentException 'Failed to decode image. The provided image must be a Bitmap.' I'm porting an application from XF to Maui I've made sure my images for the pins were added correctly.  Your demo project works fine for me.  So I'm not sure what the actual problem is.  I think it still may be something within my application not the library, But I did want to see if you may have any ideas why it could be failing.  The image that I'm using is a .png.

### ACTUAL SCREENSHOTS/STACKTRACE

```
// Paste stacktrace/screenshots/recordings
```

### EXPECTED BEHAVIOR 
```
// Write about the behavior what you expected
```

### HOW TO REPRODUCE
```
// code and steps to reproduce
```
![image](https://github.com/themronion/Maui.GoogleMaps/assets/539102/0988464f-a94b-45ba-ab6f-5778d8c2a0cc)

1. 
2. 
3.

**Comment by themronion** [comment]
> I've made sure my images for the pins were added correctly.

Well, that sounds like a lie :) 
Please check my sample where my images for pins are located and how i load them
