### ISSUE TITLE
global namespace

### ISSUE THREAD

**Issue by vedatozkanTr** [themronion/Maui.GoogleMaps#16]
Mauiprogram.cs
using Camera.MAUI;
using CommunityToolkit.Maui;
using Maui.GoogleMaps.Hosting; 

when build error;
/Users/...../Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Page.xaml.sg.cs(19,19): Error CS0400: The type or namespace name 'Maui' could not be found in the global namespace (are you missing an assembly reference?) (CS0400)

**Comment by themronion** [comment]
Not enough information. If you are referencing a dotnet 7 project then try to declare your namespaces like this:
```csharp
#if ANDROID || IOS
using Maui.GoogleMaps.Hosting;
#endif
```
