### ISSUE TITLE
Can't build an iOS app using Visual Studio on Windows

### ISSUE THREAD

**Issue by codercampos** [themronion/Maui.GoogleMaps#18]
### VERSIONS

* Maui.GoogleMaps - 5.0.1
* .NET SDK - 7.0.86

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
```
Running the iOS version of a Maui app using Visual Studio with Maui.GoogleMaps library generates a clang++ error when tries to bind the library. Running the project on macOS doesn't have this issue.

This have been tested using an M1 Macbook.

Android is working as expected.
```

### ACTUAL SCREENSHOTS/STACKTRACE

```
Error clang++ exited with code 1:
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/codercampos/Library/Caches/Xamarin/mtbs/builds/MauiGoogleMaps/57577671acee31fef62d29b50a36185f3e40cd1df654067ac25413fb41bebe33/C:/Users/coder/AppData/Local/XamarinBuildDownloadCache/GMps-6.0.1/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)	MauiGoogleMaps	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7099\targets\Xamarin.Shared.Sdk.targets	1274	
```

### EXPECTED BEHAVIOR 
```
The app should build and run on iOS even without using the control on any ContentPage.
```

### HOW TO REPRODUCE

1. Create a new Maui App solution.
2. Add Maui.GoogleMaps nuget package.
3. Build the project setting the target to iOS.
4. In the middle of the process, this will throw an error.

Repo
https://github.com/codercampos/MauiGoogleMaps

**Comment by themronion** [comment]
This is a known issue in dotnet, not specific to this nuget, however it affects the lib that is used by this nuget. Please search xamarin/macios github to resolve this error

**Comment by codercampos** [comment]
Yes, you are right. I was wondering if this was a problem with the library itself. Thanks for the lead. I'm able to build on Windows now.

**Comment by t-macintosh** [comment]
I'm getting a similar error using v 6.2.0 when Linker is used. 

`C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net9.0_18.2\18.2.9173\targets\Xamarin.Shared.Sdk.targets(930,3): error : ILStrip failed for obj/Release/net9.0-ios/ios-arm64/linked/Google.Maps.Utils.iOS.dll: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

Is there a solution out there to work-around this issue? I've tried not using Linker but that compiles all of the Google.Utils.iOS libraries meaning adding NSUsageDescriptions for things the app doesn't use like Siri etc.

**Comment by plppp2001** [comment]
You can't. You need to connect to a Mac and build it on there.

www.PaulAstramowicz.com
________________________________

**Comment by t-macintosh** [comment]
The error is also occurring in a DevOps Build Pipeline which uses a macos host to build the app. 

`Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.2/18.2.9180/targets/Xamarin.Shared.Sdk.targets(930,3): error : ILStrip failed for obj/Release/net9.0-ios/ios-arm64/linked/Google.Maps.Utils.iOS.dll: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') [/Users/runner/work/1/s/DSG.IoT.Mobile/DSG.IoT.Mobile.csproj::TargetFramework=net9.0-ios]
`

I added `<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>` to the .csproj and it seemed to build when deploying to an iOS device from Visual Studio but when trying from the pipeline still failed with the same error.
