### ISSUE TITLE
Add .Net8 target

### ISSUE THREAD

**Issue by ielbury** [themronion/Maui.GoogleMaps#23]
### SUMMARY
```
Would it be possible to add a .Net 8 target
```

### PLATFORMS

- [x] Android
- [x] iOS

The work has been done in this repository. https://github.com/n13tz5ch3/Maui.GoogleMaps/commit/a831e24c47b40a2d72ec90f5d9e9db104969ba25

It would be nice to have a new Nuget.

Thanks

**Comment by themronion** [comment]
done in #25
