### ISSUE TITLE
Need to secure API Key

### ISSUE THREAD

**Issue by AjayChauhan-Artesian** [themronion/Maui.GoogleMaps#24]
### SUMMARY
```
Suggest any way out to secure the Api_key from Attackers and unecessary usage.
```
### DETAILS

```
Hey, I have used your Google Maps package in my Maui app for embedding and rendering pins over it. But on publishing the app, Api_key will go along with the assembly. On Decompiling and Unzipping the packages, the Api_key will be retrieved. Please Suggest possible way to secure the Api_key from Attackers and unecessary usage.
```

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
There is no need to secure this key. First of all, native map sdk for android and ios is unlimited and free. Second of all if u need to apply restrictions for the key everything is done in your google console project:

![Screenshot_20240109-135011_Chrome](https://github.com/themronion/Maui.GoogleMaps/assets/52563426/c351d6e9-616d-47ba-bb74-a5fc435edf33)

**Comment by AjayChauhan-Artesian** [comment]
But I haven't used Maps SDK from Google Cloud, instead I have used Onion Google Maps nuget package for rendering map.
Also my api key is situated with Places API service for getting the results. That's why i need to secure my key. I have already review the Cloud console restriction part. But For ios and android restriction it requires Maps SDK for iOS/Android.

**Comment by themronion** [comment]
My package under the hood uses these native sdks. If u use any paid services from google then there is no need to embed the key within the app. Get it from a secure API call to your server endpoint or whatever. Use different keys for displaying the map and making calls to Places API

**Comment by AjayChauhan-Artesian** [comment]
Now I haven't use the Api key for rendering the map and it says, it requires an Api key.
![image](https://github.com/themronion/Maui.GoogleMaps/assets/108712841/58dbe487-4e1e-4691-a0e8-33a3f01911b9)

**Comment by themronion** [comment]
🤦‍♂️ Have i told u not to use an API key? Please reread my comment. And man. This is not a question about the library. Please google best practices for storing api keys
