### ISSUE TITLE
The map layer is not displayed on physical iOS device

### ISSUE THREAD

**Issue by RsZoli** [themronion/Maui.GoogleMaps#29]
### VERSIONS

* Maui.GoogleMaps - 5.0.3
* .NET SDK - 8.0.100

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
```
The map is not being displayed on physical iOS devices
```

### ACTUAL SCREENSHOTS/STACKTRACE

```
![IMG_0380](https://github.com/themronion/Maui.GoogleMaps/assets/28480037/9265f11d-d5df-459e-9798-d49715585a1b)

![IMG_0381](https://github.com/themronion/Maui.GoogleMaps/assets/28480037/3ced62c6-8a49-4f5b-a213-e5cf9845b183)
```

### EXPECTED BEHAVIOR 
```
The map is displayed
```

### HOW TO REPRODUCE
```
Just install and try to use the NuGet
```

Dear Friend, could you help me with this? As you can see on my screenshots, on iOS the map layers are not being display in the map control, however positioning is working and i also can put up markers!

Thank you very much!

**Comment by plppp2001** [comment]
The latest version works fine in .NET 8 MAUI.  Did you enable google maps for your map KEY for both IOS and Android on the google maps settings on your account?

Did you do this?:

![image](https://github.com/themronion/Maui.GoogleMaps/assets/45370058/45f149a4-8185-48eb-9d75-8f28b0c7b341)

**Comment by themronion** [comment]
Please follow the setup guide in repo Readme.md

**Comment by RsZoli** [comment]
> The latest version works fine in .NET 8 MAUI. Did you enable google maps for your map KEY for both IOS and Android on the google maps settings on your account?
> 
> Did you do this?:
> 
> ![image](https://private-user-images.githubusercontent.com/45370058/304254663-45f149a4-8185-48eb-9d75-8f28b0c7b341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTAyNTMsIm5iZiI6MTcwNzgwOTk1MywicGF0aCI6Ii80NTM3MDA1OC8zMDQyNTQ2NjMtNDVmMTQ5YTQtODE4NS00OGViLTlkNzUtOGYyOGIwYzdiMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA3MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDg4YTc3ZjM4ZTY2MTgyNTI1MWZmYTA0OGVkMGFkOTllYTgzYjM0YzE2ODU4OGMzYjE5OTg1NzhjZmVjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tKSueELejqVcxs8LiKWqqmyx7B8FiS-nD_mrd0gMmuY)

Yes, of course I did it! It is an old key, it has no application nor any api restrictions.

**Comment by RsZoli** [comment]
> Please follow the setup guide in repo Readme.md

I absolutely did by the letter, I have no errors, no exceptions, nothing to start debugging with! :/
