### ISSUE TITLE
Possibility to use Google My Map to add an individual map with my own pins

### ISSUE THREAD

**Issue by CHLINDE** [themronion/Maui.GoogleMaps#3]
I am missing a feature to use my own google map. Is it still possible or is it possible to implement this feature?

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
Please elaborate what do u mean by "my own google map". Custom pins are supported, please check repo sample.

**Comment by CHLINDE** [comment]
I like to use the "My maps" function from google:
https://www.google.com/maps/about/mymaps/

There I can set my own pins which are stored on google servers,
I like to display this individual map in my app

**Comment by themronion** [comment]
As far as i understand this is a completely different product not connected to mobile sdks for android and ios. You can always try displaying your map in a WebView and see how that goes. Or just open your customized map by the google app installed on users' phones
