### ISSUE TITLE
Sample project not working on IOS

### ISSUE THREAD

**Issue by alikoli** [themronion/Maui.GoogleMaps#33]
### VERSIONS

* Maui.GoogleMaps - x.x.x
* .NET SDK - x.x.x

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
CachingImageFactory does not implement IImageFactory interface.
Method should have signature: public UIImage ToUIImage(BitmapDescriptor descriptor, IMauiContext mauiContext)
When I try to run: MainPage = new NavigationPage(new BindingPinViewPage());
I get:
Object reference not set to an instance of an object.'. Callstack: '   at Maui.GoogleMaps.Logics.iOS.UiSettingsLogic.OnUpdateCompassEnabled() 

In this line Settings is null:
NativeMap.Settings.CompassButton = Map.UiSettings.CompassEnabled;

### EXPECTED BEHAVIOR 
Sample project works.

**Comment by alikoli** [comment]
Any update on this? I tried to use this library in my project with no success, but when even the sample project does not work I gave up. Are there any plans to make a working version for ios?

**Comment by plppp2001** [comment]
> Any update on this? I tried to use this library in my project with no success, but when even the sample project does not work I gave up. Are there any plans to make a working version for ios?

Hey there's a sample posted you can open up in visual studio and you could run it locally and it works no problem for both platforms for try that out first and look at the code there it's working for me with Maui 8, both Android and ios.

**Comment by themronion** [comment]
@alikoli What problems did u have? Did u browse the closed issues for similar ones?

**Comment by themronion** [comment]
fixed in https://github.com/themronion/Maui.GoogleMaps/commit/dbc7229543b219cded01af79ba81e52e903e5a5d
