### ISSUE TITLE
Is there any way to update the google API key after the Google Map initialized from MAUI Program.

### ISSUE THREAD

**Issue by sunilsolanki-alight** [themronion/Maui.GoogleMaps#38]
### SUMMARY
Is there any way to update the google API key after the Google Map initialized from MAUI Program 

### DETAILS
We are getting this key from backend service and wanted to update once, key reciewved from api 

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
> Is there any way to update the google API key after the Google Map initialized from MAUI Program

no
