### ISSUE TITLE
Cannot Deploy to Simulator on Apple Silicon

### ISSUE THREAD

**Issue by scottertz** [themronion/Maui.GoogleMaps#41]
### VERSIONS

* Maui.GoogleMaps - 5.0.3
* .NET SDK - 8.0.201

### IDE

- [x] Rider
- [x] Visual Studio
- [x] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
When deploying to an iOS Simulator on a Mac with Apple Silicon (M1, M2, M3), you get a build exception. This happens when building on the Mac using VS for Mac or Rider, as well as deploying from Windows using a paired Mac. Running the same code against a Simulator on an Intel Mac works fine.

Here is a similar issue Microsoft App Center faced early on with some information. The workaround in the bug report doesn't work for this package:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755

### ACTUAL SCREENSHOTS/STACKTRACE
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : clang++ exited with code 1: [/Users/scottertz/SEG/SEG_MobileApp/SegMobile/SegMobile/SegMobile.csproj::TargetFramework=net8.0-ios]
 
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/scottertz/Library/Caches/XamarinBuildDownload/GMps-6.0.1/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64 [/Users/scottertz/SEG/SEG_MobileApp/SegMobile/SegMobile/SegMobile.csproj::TargetFramework=net8.0-ios]
 
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/scottertz/SEG/SEG_MobileApp/SegMobile/SegMobile/SegMobile.csproj::TargetFramework=net8.0-ios]

### EXPECTED BEHAVIOR 
Expect the package to be compatible with all Simulator configurations. The package has to be built to support Apple Silicon Simulators.

### HOW TO REPRODUCE
[code and steps to reproduce]

1. Create clean MAUI application on Apple Silicon Mac.
2. Install Nuget package.
3. Try to deploy.

**Comment by themronion** [comment]
Sometimes i wonder how you guys even became programmers... check the sample csproj or xamarin/macios repo for workarounds

**Comment by JairoMarques** [comment]
As @themronion said:

	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
		<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
	</PropertyGroup>

**Comment by Barry-Theunissen** [comment]
Still not working...for .NET9...I get this... 

clang++ exited with code 1:
ld: building for 'iOS-simulator', but linking in object file (/Users/barrytheunissen/Library/Caches/Xamarin/mtbs/builds/aeromura/312e2cc3be7da01c2e0e08614d116234d5df60ff0eaea2d26e08e26fcd272dde/C:/Users/bdthe/.nuget/packages/xamarin.google.maps.utils/1.3.9/lib/net8.0-ios17.2/Google.Maps.Utils.iOS.resources/GoogleMapsUtils.framework/GoogleMapsUtils[arm64][2](GoogleMapsUtils_vers.o)) built for 'iOS'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I added this to my project file, as suggested:

<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
	<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
</PropertyGroup>

Added the PropertyGroup to my project file with the Condition = "'$TargetFramework' == 'net9.0-ios'" and the RunTimeIdentifier of iossimulator-x64

Does not help. Will not build the project for iOS, does not matter if I run the simulator on my x86 machine or remotely on my Mac Mini M1.

Its not clear in the sample that we need to do this

**Comment by Barry-Theunissen** [comment]
Still not working at all for .NET 10 either...won't even build now....the sample project, for iOS...see attached screenshot....

<img width="1206" height="590" alt="Image" src="https://github.com/user-attachments/assets/86ec3847-9b08-45ff-8a9e-6d95b283db73" />
