### ISSUE TITLE
Docs docs docs please 😭😭😭

### ISSUE THREAD

**Issue by tanakamawere** [themronion/Maui.GoogleMaps#42]
### SUMMARY
How do I install this, how do I implement it? What are the customisation options? No idea because there are no docs 

### DETAILS
Please add docs

### PLATFORMS

- [x] Android
- [x ] iOS

**Comment by themronion** [comment]
You have a whole sample project to explore. Installation is in the Readme.md. All other docs on usage is in the original repo from which this one is forked.

**Comment by tanakamawere** [comment]
But that doesn't tell you what everything does...

For example, I'm trying to move the camera between from showing one pin to showing two pins with animation. Whenever I do it, it goes to the wrong place, not sure if that's what bounds are for.
Or trying to draw a path along the road like Google Maps does for navigation, I'm really going roundnin circles figuring out what the best way to do that is

Please link the usage docs from the forked repo. I rummaged through it but couldn't find any usage docs

**Comment by plppp2001** [comment]
The sample project works perfectly fine and you can put all functionality into debug mode np. I use it all the time.

________________________________

**Comment by tanakamawere** [comment]
@plppp2001 it works properly. What I mean is having explicit docs for integration instead of having to go a specific implementation and then starting to mix and match it to fit your own implementation
