### ISSUE TITLE
Support for Polyline Line Types

### ISSUE THREAD

**Issue by ajay-mundi** [themronion/Maui.GoogleMaps#43]
### SUMMARY
Support for polyline line types.

### DETAILS

Would like to be able to add different polyline line types such as dotted,  double line, perhaps other styles and patterns as mentioned here https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/470). 

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
Prs are welcome

**Comment by themronion** [comment]
closed by #50
