### ISSUE TITLE
Adding an option for clustering 

### ISSUE THREAD

**Issue by FreakyAli** [themronion/Maui.GoogleMaps#44]
### SUMMARY

Add clustering for Android and iOS using the utils library, An example for it is available in Xamarin Forms here : https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering

### DETAILS
I don't think details would be required its a very common functionality available in the utils 

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
@FreakyAli if u need it go ahead and add it. I am open to prs

**Comment by FreakyAli** [comment]
I am currently working on something else, but I'll definitely try to add it once I find some time, I would appreciate if you could create a basic document that outlines the handlers that you've created for ease of work

**Comment by themronion** [comment]
https://github.com/themronion/Maui.GoogleMaps/pull/57#issuecomment-2322909855
