### ISSUE TITLE
Unable to use for ios simulator: building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by GreenleafDk** [themronion/Maui.GoogleMaps#48]
### VERSIONS

* Maui.GoogleMaps -5.0.3
* .NET SDK - 8.0

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
Emulator for android works, but attempting to run on ios simulator fails with
building for iOS Simulator, but linking in object file built for iOS

### HOW TO REPRODUCE
Load sample project from repo and launch on ios simulator

**Comment by plppp2001** [comment]
You have to run the simulator on the actual mac computer. Do not use hot reload, it doesn't work with map.

**Comment by GreenleafDk** [comment]
Thanks for responding. I am running the simulator on the mac, which is the only way to run it. Visual studio connects to physical mac, simulator is selected and then project is being run. In building before run, it fails. Seemingly because of the processor architecture used for the package, which is incompatible with simulator...?
I may be confused, as I have never experienced this kind of issue before.

**Comment by GreenleafDk** [comment]
I should perhaps ask a side question. Has anyone else here confirmed run the demo project on an iOS 17.5 simulator? The repro step seem very easy and clear in that regard.

**Comment by themronion** [comment]
Duplicate. https://github.com/themronion/Maui.GoogleMaps/issues/41
