### ISSUE TITLE
The maps on IOS will break and not view. still works on android

### ISSUE THREAD

**Issue by LukeAplymouth** [themronion/Maui.GoogleMaps#5]
### VERSIONS

* Maui.GoogleMaps - x.x.x
* .NET SDK - x.x.x

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
```Map on IOS debug device does not display.

// Write about of your problem
```I noticed that the map wouldn't show on the IOS debug device and attempted to fix by recreating the project a few times. Sometimes the app will work and show and a lot of others it doesn't. the fix is also temperamental as I could fix it then either move my project copy or add something to it and it would stop.

### ACTUAL SCREENSHOTS/STACKTRACE

```
// Paste stacktrace/screenshots/recordings
```

### EXPECTED BEHAVIOR 
```
// Write about the behavior what you expected
```

### HOW TO REPRODUCE
``` Rather happily to reproduce the issue I create a new project and literally follow this video https://youtu.be/775rzp2U82M?list=PLuuQEcfDL8IIuGxEketUPMUsbZ_CAcL3X. Had it not work a bunch of times and then occasionally it would work. 
Also building on a mac if that means anything.
// code and steps to reproduce
```
I literally followed the video step by step

This may be something to do with why its not displaying on ios but I get the same warning on android and it works okay.
<img width="749" alt="Screenshot 2023-04-24 at 21 05 20" src="https://user-images.githubusercontent.com/115366868/234105362-c334f65d-47f5-45aa-ac6f-e0ba548050b8.png">

Thanks in advance

**Comment by themronion** [comment]
I didn't experience such problems, nor everyone else who used this library, so probably in such cases there is something wrong with your environment or Visual Studio.
