### ISSUE TITLE
Google cloud map style and map id

### ISSUE THREAD

**Issue by Maniacy2k** [themronion/Maui.GoogleMaps#56]
### SUMMARY
It would be good to either add an example or implement the assigning of map id to import the google cloud map style instead of via the json file as found [here](https://github.com/themronion/Maui.GoogleMaps/blob/maui/sample/MauiGoogleMapSample/MapStylePage.xaml.cs)

### DETAILS
An example on the google docs [here](https://developers.google.com/maps/documentation/get-map-id)

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by themronion** [comment]
If u need it, u do it) that's how we work in this repo. Prs are welcome. Keep in mind though, that iOS uses a very old version of the native lib and this may not be available there

**Comment by themronion** [comment]
Update on this one, the iOS sdk is now 9.1.1 so most likely if all the needed code is in the new bindings this can be implemented

**Comment by andersonvieiragomeslopes** [comment]
Hi @themronion @Maniacy2k 

I started the implementation, and Android seems fine, but on iOS, the interfaces are missing.

#83

**Comment by themronion** [comment]
done in 277984f6014c566466d70a18d836968566d9675b
