### ISSUE TITLE
Building for iOS Simulator, but linking in object file built for iOS + Error in androidx/collection/ArrayMapKt.class:

### ISSUE THREAD

**Issue by mindport** [themronion/Maui.GoogleMaps#58]
### VERSIONS

* Maui.GoogleMaps - 5.1.2
* .NET SDK - 8.0 

### IDE

- [ ] Rider
- [] Visual Studio
- [x] Visual Studio for Mac
- [x ] VSCode for Mac

### PLATFORMS

- [x ] Android
- [x] iOS

### ACTUAL BEHAVIOR
error : clang++ exited with code 1 when adding package to fresh maui project 

### ACTUAL SCREENSHOTS/STACKTRACE
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : clang++ exited with code 1: [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/jensengelbrecht/Library/Caches/XamarinBuildDownload/GMps-6.0.1/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64 [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-ios]
MSBUILD : java error JAVA0000: Error in /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class: [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Compilation failed [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: androidx/collection/ArrayMapKt.class [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:135) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.main(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:5) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at Version.fakeStackEntry(Version_8.2.33.java:0) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.T.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:5) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:82) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:32) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:31) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.b(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:2) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:42) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.b(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:13) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:40) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:122) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  ... 1 more [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.utils.b: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/jensengelbrecht/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.Q2.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:21) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.D2.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:54) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.D2.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:10) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.D2.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:6) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.graph.m4$a.d(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:6) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.dex.c.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:61) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.dex.c.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:12) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.dex.c.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:9) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:45) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.d(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:17) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.D8.c(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:69) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  at com.android.tools.r8.utils.S0.a(R8_8.2.33_429c93fd24a535127db6f4e2628eb18f2f978e02f99f55740728d6b22bef16dd:28) [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  ... 6 more [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  [/Users/jensengelbrecht/Projects/GeoStoryMauiNew/GeoStoryMauiNew/GeoStoryMauiNew.csproj::TargetFramework=net8.0-android]

### EXPECTED BEHAVIOR 
Compile and debug

### HOW TO REPRODUCE

1. Create new maui project in VSCode for Mac
2. add latest package
3. build

**Comment by themronion** [comment]
How about first browsing the repo issues and then posting an issue. Or at least check out the sample app. Closing as duplicates
