### ISSUE TITLE
Tilt map using two fingers

### ISSUE THREAD

**Issue by Hrishikesh46779** [themronion/Maui.GoogleMaps#60]
### SUMMARY
In xamarin, we can use two fingers to tilt the map. But this is not happening in this Maui library or am I missing something?

**Comment by themronion** [comment]
Probably you are. Check sample app

**Comment by plppp2001** [comment]
Works for me just fine.


________________________________
From: Hrishikesh46779 ***@***.***>
Sent: Saturday, August 31, 2024 3:04:17 PM
To: themronion/Maui.GoogleMaps ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [themronion/Maui.GoogleMaps] Tilt map using two fingers (Issue #60)


SUMMARY

In xamarin, we can use two fingers to tilt the map. But this is not happening in this Maui library or am I missing something?

**Comment by Hrishikesh46779** [comment]
Ok I was missing Map.UiSettings.TiltGesturesEnabled = true; 
 I think this property is set to true by default in xamarin library. Thank you.
