### ISSUE TITLE
ToScreenLocation throws null reference on iOS but works on Android

### ISSUE THREAD

**Issue by GreenleafDk** [themronion/Maui.GoogleMaps#61]
### VERSIONS

* Maui.GoogleMaps - 6.0.0
* .NET SDK - 8.0

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS, physical device iphone 14 iOS 17.6.1

### ACTUAL BEHAVIOR
ToScreenLocation(some Position) throws NullReferenceException
because the delegate is not set, but is null, here

public Point ToScreenLocation(Position position)
{
    if (OnToScreenLocation == null)
    {
        throw new NullReferenceException("ToScreenLocation");
    }

    return OnToScreenLocation(position);
} 

### EXPECTED BEHAVIOR 
Expect the screen position for the given Position on the map, which is what happens on android. This error is only seen on iOS 

### HOW TO REPRODUCE
Make a map and call the method on an iOS device

**Comment by themronion** [comment]
@GreenleafDk feel free to open a pr and fix it

**Comment by themronion** [comment]
fixed in 6c9e085f8efad4e8a5e120ebe7a796773d481bf1
