### ISSUE TITLE
Programmatically show pin with annotations

### ISSUE THREAD

**Issue by LeoJHarris** [themronion/Maui.GoogleMaps#64]
Not sure if this is supported already but I couldn't find a way to programmatically show the pin with annotations as shown below, this was only after I manually tapped the pin.

<img src="https://github.com/user-attachments/assets/eddbf7ef-d26a-4453-9d35-b9ba1db86f4e" width="400">

My use case is I have a button on the map that spans to a pin but currently I have to manually tap the pin to actually get the annotation / box with pin details to show up.

I currently have the following calls with no success.
```csharp
StoresMap.SendInfoWindowClicked(pin);
bool wasSuccess =  StoresMap.SendPinClicked(pin);
StoresMap.SendSelectedPinChanged(pin);
```

The `wasSuccess` is always false so I checked to see if the `pin` provided to the `SendPinClicked` exists in the list of pins and seems to be the pin I want to highlight.

Any help is greatly appreciated.

**Comment by themronion** [comment]
Please explore the sample app prior posting questions here. It has everything and even more to answer your question
