### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by jduncalf** [themronion/Maui.GoogleMaps#65]
### VERSIONS

* Maui.GoogleMaps - 6.0.0.0
* .NET SDK - 8 core

### IDE

- [ ] Rider
- [x] Visual Studio 2022
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
Cannot build a .NET MAUI app due to "Undefined symbols for architecture arm64: _GMSGeometryArea ........." etc.

**Comment by themronion** [comment]
Try building on a mac. Also check sample app.

**Comment by jduncalf** [comment]
Build on a Mac how, its's a test .net maui app. VS2002 paired with a Mac. The sample includes the source and doesn't reference the nuget package?
