### ISSUE TITLE
.NET MAUI app doesn't build once Nuget package is referenced.

### ISSUE THREAD

**Issue by jduncalf** [themronion/Maui.GoogleMaps#66]
### VERSIONS

* Maui.GoogleMaps - 6.0.0
* .NET SDK - 8 core

### IDE

- [ ] Rider
- [x] Visual Studio 2022
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
Siply refernceing the nuget package Onion.Maui.GoogleMaps breaks the build of a straightforward .Net MAUI app:

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\targets\Xamarin.Shared.Sdk.targets(1641,3): error : clang++ exited with code 1:
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\targets\Xamarin.Shared.Sdk.targets(1641,3): error : Undefined symbols for architecture arm64:
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\targets\Xamarin.Shared.Sdk.targets(1641,3): error :   "_GMSGeometryArea", referenced from:

### ACTUAL SCREENSHOTS/STACKTRACE
[Paste stacktrace/screenshots/recordings]

### EXPECTED BEHAVIOR 
[Write about the behavior what you expected]

### HOW TO REPRODUCE
[code and steps to reproduce]

1. 
2. 
3.

**Comment by themronion** [comment]
Duplicate #41

**Comment by jduncalf** [comment]
Test app found at https://github.com/jfversluis/MauiGoogleMapsSample seems to build fine. However, does not run on iOS. Android only.
