### ISSUE TITLE
PinClickedEventArgs Handled

### ISSUE THREAD

**Issue by mindport** [themronion/Maui.GoogleMaps#69]
### VERSIONS

* Maui.GoogleMaps - 6.0.0
* .NET SDK - 8.0.0

### IDE

- [ ] Rider
- [] Visual Studio
- [ ] Visual Studio for Mac
- [x ] Visual Studio Code Mac

### PLATFORMS

- [x ] Android
- [x]  iOS

### ACTUAL BEHAVIOR
It seems that when clicking on a pin and making it selected I can't hide the tooltip
I think it should be closed when setting the PinClickedEventArgs property Handled to true?

### ACTUAL SCREENSHOTS/STACKTRACE
![Screenshot 2024-09-17 at 11 44 15](https://github.com/user-attachments/assets/b94b0fc8-fd96-4a7e-9cc1-395d693743ce)

### EXPECTED BEHAVIOR 
The pin tooltip should be hidden even if pin is selected if Handled is set to true

### HOW TO REPRODUCE
Nothing special, maybe creating custom pins have an affect?

**Comment by themronion** [comment]
No, this is intended behavior. If you don’t want the tooltip don’t make it selected

**Comment by mindport** [comment]
Ooh, okey so it differs from original Google Maps then? How would I go about to hide the tooltip when selecting a pin?

**Comment by mindport** [comment]
I mean what does the handled property do then?

**Comment by themronion** [comment]
It does hide the tooltip. The problem is that most likely you are setting the SelectedPin property or whatsoever. Please see sample app for different scenarios.

**Comment by mindport** [comment]
Ok, I will look, it's just that it worked with Xamarin.Forms.Googlemaps so something has changed in functionality. But sure I'll check.
