### ISSUE TITLE
iOS GoogleMaps bindings upgrade

### ISSUE THREAD

**Issue by AdamEssenmacher** [themronion/Maui.GoogleMaps#72]
### SUMMARY
The iOS side of this plugin uses Microsoft's Xamarin.Google.iOS.Maps nuget. Microsoft abandoned their support for all Google / Firebase libraries and [archived the project](https://github.com/xamarin/GoogleApisForiOSComponents/tree/main/source/Google/Maps).

After Microsoft announced they were discontinuing support, I created a [community-supported fork](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents) of the repo and published updated [replacement packages](https://www.nuget.org/profiles/adamessenmacher) for the Firebase libraries, which have since been adopted by [Plugin.Firebase](https://github.com/TobiasBuchholz/Plugin.Firebase) and [BarcodeScanner.Mobile](https://github.com/JimmyPun610/BarcodeScanner.Mobile)

Thanks to a major contribution from @[Digifais](https://github.com/Digifais), we were able to bring GoogleMaps into the fold this week and [publish bindings](https://www.nuget.org/packages/AdamE.Google.iOS.Maps) built against native library version 9.1.1 (latest). The last Microsoft package was built on [6.0.1](https://developers.google.com/maps/documentation/ios-sdk/release-notes#2021-12-09). Perhaps this plugin could migrate to the new package.

### PLATFORMS

- [] Android
- [x] iOS

**Comment by themronion** [comment]
Amazing! Will do!

**Comment by themronion** [comment]
@AdamEssenmacher I have tried with no luck, see https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/issues/50

Fails with my project as well as with a template one

**Comment by AdamEssenmacher** [comment]
I had a merge snafu with the latest patch. Should be fixed with 9.1.1.2.

**Comment by themronion** [comment]
all good now

**Comment by themronion** [comment]
done d789a6bf499dd696898692f359813908a35afa68
Enjoy, folks!
