### ISSUE TITLE
Cant' compile little sample with nuget 6.0.1

### ISSUE THREAD

**Issue by TFreudi1** [themronion/Maui.GoogleMaps#74]
### VERSIONS

* Maui.GoogleMaps - 6.0.1
* .NET SDK - 8.0.82

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS
- [x] Android

### ACTUAL BEHAVIOR
I  made a simple Demo. when I try to compile I get an error:
MSBUILD : java.exe error JAVA0000: Error in F:\Nuget\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class 

### ACTUAL SCREENSHOTS/STACKTRACE
![grafik](https://github.com/user-attachments/assets/9347c53f-dcf2-4826-b9ef-bc889a807ce4)

### HOW TO REPRODUCE
Take my sample project and try to compile Android part.

[MauiOnionGooglemap.zip](https://github.com/user-attachments/files/17618756/MauiOnionGooglemap.zip)

**Comment by themronion** [comment]
Duplicate #28
