### ISSUE TITLE
Question: Is It Possible To De-Google And Only Use OSM Tiles?

### ISSUE THREAD

**Issue by T-T-P** [themronion/Maui.GoogleMaps#75]
Firstly, thank you for maintaining this project, your dedication is greatly appreciated!

I was playing around with OSM tiles using the code sample from TilesPage.xaml.cs and it made me wonder:
Is it possible to load the Onion.Maui.GoogleMaps package without a Google API key and just use the map functionality with OSM tiles?

**Comment by themronion** [comment]
No. What is the problem to use a key though? iOS and Android mobile sdks are non chargeable by Google

**Comment by T-T-P** [comment]
Yes, I was just thinking worst case scenario such as they start charging for the mobile sdks like they did with the javascript ones some years back
