### ISSUE TITLE
Stuck in compiling

### ISSUE THREAD

**Issue by TFreudi1** [themronion/Maui.GoogleMaps#76]
### VERSIONS

* Maui.GoogleMaps - 6.0.1
* .NET SDK - 8.0.92

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [x] Android
- [ ] iOS

### ACTUAL BEHAVIOR
I can run the sample via Debug, but when I try to build a release build or try to publish it hangs for ever.
see screenshot 

### ACTUAL SCREENSHOTS/STACKTRACE
![grafik](https://github.com/user-attachments/assets/363842b8-26cc-4a72-a460-009bb1931647)

### EXPECTED BEHAVIOR 
Building should finish.

### HOW TO REPRODUCE
1. Check out project from git
2. Change to release mode
3. start rebuild all of MauiGoogleMapSample

**Comment by themronion** [comment]
Please build on mac. And why the hell would you even need to build a sample app in Release mode. Don’t waste your time

**Comment by TFreudi1** [comment]
I took the sample project as easy to track example. The real problem is my own project where I included also both projects from the lib path like you did in the sample project.
I need an Android APK. With "build on mac" you mean "User Rider on Mac" ? At the moment i'm only interested on teh android part not ios.

**Comment by themronion** [comment]
Why you need to include my projects, just install a nuget

**Comment by TFreudi1** [comment]
Because I want to Debug your project also to see how you did some things and I add functionality, for example showing the Info Window of all pins with a functioncall... 
I know I can use the nuget package, inheritance ... but including the project itself  was easier. But don't waste your time , I thought somebody had a hint like "remove nugatpackage logic" from the csproj or something similiar, but if you haven't I musst find a solution by myself. Thanky anyway for the quick response. I will let this open until I find a solution what prevent the realse build from finishing. Btw. it is the same with Rider and  the preview version of VS2022.

**Comment by TFreudi1** [comment]
I see you closed it, it'closed for me too, I can't compile in Android-Release Mode nor build a APK. Even if I only use the nuget package. I can't see why even wit  maximum build diagnostics it just stuck.
