### ISSUE TITLE
dotnet 9.0 ios map not showing

### ISSUE THREAD

**Issue by Th3L0x** [themronion/Maui.GoogleMaps#78]
### VERSIONS

* Maui.GoogleMaps - 6.0.1
* .NET SDK - 9.0

### IDE

Visual Studio Code (Mac)

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
The shell of the map is  being loaded but the map it self not showing or not visible. (Custom objects are visible, like circle or pin)
![error](https://github.com/user-attachments/assets/a85aa814-138b-4e9d-a819-d8c54cd9f857)

On android works fine.

Am I missing something? I'm using the same api key for ios and android too.
In the sample the two platforms are using the same key too.

**Comment by themronion** [comment]
Have u tried on dotnet 8? If it doesn’t work there then the issue is with the key. Try putting my key instead of yours.

**Comment by Th3L0x** [comment]
With you key its working,  do you have any hint how to create this type of key?

**Comment by themronion** [comment]
Just follow closely any guide out there in the internet
