### ISSUE TITLE
The map not showing in archived app

### ISSUE THREAD

**Issue by Th3L0x** [themronion/Maui.GoogleMaps#85]
### VERSIONS

* Maui.GoogleMaps - 6.1.0
* .NET SDK - 9.0.0

### IDE

- [ ] Rider
- [x] Visual Studio Code (Mac)
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
The map not showing in release mode (archived,published to testflight), but works in debug mode.
(using the same key both in debug and release mode)

### ACTUAL SCREENSHOTS/STACKTRACE
![error](https://github.com/user-attachments/assets/e5d06691-edc8-4ba2-a483-3b12e7268028)

### EXPECTED BEHAVIOR 
The map is showin as in debug mode.

### HOW TO REPRODUCE

This is my  ios config in csproj:

```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
    <ApplicationId>com.company.Test</ApplicationId>
    <ApplicationTitle>Test</ApplicationTitle>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>True</MtouchDebug>
    <EmbedOnDemandResources>True</EmbedOnDemandResources>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
    <ApplicationId>com.company.Test</ApplicationId>
    <ApplicationTitle>Test</ApplicationTitle>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
    <MtouchLink>None</MtouchLink>
    <MtouchInterpreter>all</MtouchInterpreter>
    <UseInterpreter>true</UseInterpreter>
    <MtouchUseLlvm>false</MtouchUseLlvm>
    <EmbedOnDemandResources>True</EmbedOnDemandResources>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
  </PropertyGroup>
```

**Comment by BlackZero1122** [comment]
@Th3L0x, I have the same issue on .net 8. How did you resolve this?

**Comment by Th3L0x** [comment]
The issue was on my end, specifically with my API key. To resolve it, I recreated the key and enabled iOS functionality in my Google Cloud Console. After this step, when I created the new key and clicked "Restrict Key," I was able to select the 'iOS application' restriction (or something like that). This change ensured that my key remains active on iOS, even in release mode (TestFlight).
